spring.application.name=Multi-tenant-application

# Spring Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/multi_tenant_db
spring.datasource.username=postgres
spring.datasource.password=Sandeep9870@
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false

# Application JWT settings
app.jwt.secret=change-me-to-a-very-strong-secret-key-at-least-256-bits-long-for-hs512-algorithm
app.jwt.access-token-expiration-ms=900000
app.jwt.refresh-token-expiration-ms=1209600000

# Server
server.port=8080

# Logging
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG

# Swagger/OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.api-docs.path=/v3/api-docs
